<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Schema;

class AccreditationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seed accreditations
        $accreditations = [
            [
                'id' => 1,
                'title' => 'Akreditasi Program Studi Informatika',
                'description' => 'Akreditasi untuk Program Studi Informatika oleh BAN-PT',
                'type' => 'department',
                'institution_name' => 'BAN-PT',
                'grade' => 'Unggul',
                'status' => 'completed',
                'submission_date' => Carbon::now()->subYears(4),
                'visit_date' => Carbon::now()->subYears(4)->addMonths(2),
                'result_date' => Carbon::now()->subYears(4)->addMonths(4),
                'expiry_date' => Carbon::now()->addYear(),
                'period_start' => Carbon::now()->subYears(4),
                'period_end' => Carbon::now()->addYear(),
                'faculty_id' => 1,
                'department_id' => 1,
                'coordinator_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 2,
                'title' => 'Akreditasi Internasional Program Studi Informatika',
                'description' => 'Akreditasi Internasional untuk Program Studi Informatika',
                'type' => 'department',
                'institution_name' => 'ABET',
                'grade' => 'A',
                'status' => 'in_progress',
                'submission_date' => Carbon::now()->subMonth(),
                'visit_date' => Carbon::now()->addMonth(),
                'result_date' => null,
                'expiry_date' => null,
                'period_start' => Carbon::now()->subMonth(),
                'period_end' => Carbon::now()->addMonths(6),
                'faculty_id' => 1,
                'department_id' => 1,
                'coordinator_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subMonth(),
                'updated_at' => Carbon::now()->subMonth(),
            ],
        ];

        DB::table('accreditations')->insert($accreditations);

        // Seed accreditation standards
        $standards = [
            [
                'id' => 1,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C1',
                'name' => 'Visi, Misi, Tujuan dan Strategi',
                'description' => 'Standar terkait visi, misi, tujuan, dan strategi',
                'category' => 'academic',
                'weight' => 3.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 2,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C2',
                'name' => 'Tata Pamong, Tata Kelola, dan Kerjasama',
                'description' => 'Standar terkait tata pamong, kepemimpinan, dan sistem pengelolaan',
                'category' => 'management',
                'weight' => 3.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 3,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C3',
                'name' => 'Mahasiswa',
                'description' => 'Standar terkait mahasiswa',
                'category' => 'academic',
                'weight' => 3.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 4,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C4',
                'name' => 'Sumber Daya Manusia',
                'description' => 'Standar terkait sumber daya manusia',
                'category' => 'organization',
                'weight' => 4.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 5,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C5',
                'name' => 'Keuangan, Sarana dan Prasarana',
                'description' => 'Standar terkait keuangan, sarana dan prasarana',
                'category' => 'facilities',
                'weight' => 4.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 5,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 6,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C6',
                'name' => 'Pendidikan',
                'description' => 'Standar terkait pendidikan',
                'category' => 'academic',
                'weight' => 5.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 6,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 7,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C7',
                'name' => 'Penelitian',
                'description' => 'Standar terkait penelitian',
                'category' => 'research',
                'weight' => 5.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 8,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C8',
                'name' => 'Pengabdian kepada Masyarakat',
                'description' => 'Standar terkait pengabdian kepada masyarakat',
                'category' => 'community_service',
                'weight' => 5.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 8,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 9,
                'accreditation_id' => 1,
                'parent_id' => null,
                'code' => 'C9',
                'name' => 'Luaran dan Capaian Tridharma',
                'description' => 'Standar terkait luaran dan capaian tridharma',
                'category' => 'academic',
                'weight' => 6.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 9,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            // Sub-standards for C1
            [
                'id' => 10,
                'accreditation_id' => 1,
                'parent_id' => 1,
                'code' => '1.1',
                'name' => 'Kesesuaian Visi, Misi, Tujuan dan Strategi (VMTS)',
                'description' => 'Kesesuaian VMTS dengan perkembangan ilmu pengetahuan dan profesi',
                'category' => 'academic',
                'weight' => 1.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 11,
                'accreditation_id' => 1,
                'parent_id' => 1,
                'code' => '1.2',
                'name' => 'Mekanisme Penyusunan VMTS',
                'description' => 'Mekanisme penyusunan VMTS yang melibatkan pemangku kepentingan',
                'category' => 'academic',
                'weight' => 1.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 12,
                'accreditation_id' => 1,
                'parent_id' => 1,
                'code' => '1.3',
                'name' => 'Sosialisasi VMTS',
                'description' => 'Sosialisasi VMTS kepada pemangku kepentingan',
                'category' => 'academic',
                'weight' => 1.0,
                'max_score' => 100.0,
                'is_active' => true,
                'order' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
        ];

        DB::table('accreditation_standards')->insert($standards);

        // Seed accreditation documents
        $documents = [
            [
                'id' => 1,
                'accreditation_id' => 1,
                'standard_id' => 1,
                'title' => 'Dokumen Visi Misi Prodi Informatika',
                'description' => 'Dokumen visi dan misi program studi informatika',
                'document_number' => 'VM-INF-001',
                'document_type' => 'policy',
                'file_path' => 'documents/vmts-prodi-informatika.pdf',
                'status' => 'approved',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
            [
                'id' => 2,
                'accreditation_id' => 1,
                'standard_id' => 2,
                'title' => 'Manual Mutu Tata Pamong',
                'description' => 'Manual mutu terkait tata pamong dan kepemimpinan',
                'document_number' => 'MM-TP-001',
                'document_type' => 'manual',
                'file_path' => 'documents/manual-mutu-tata-pamong.pdf',
                'status' => 'approved',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subYears(4),
            ],
        ];

        DB::table('accreditation_documents')->insert($documents);

        // Seed accreditation evaluations
        $evaluations = [
            [
                'id' => 1,
                'accreditation_id' => 1,
                'standard_id' => 1,
                'title' => 'Evaluasi Standar VMTS',
                'description' => 'Evaluasi capaian standar Visi, Misi, Tujuan, dan Strategi',
                'evaluation_date' => Carbon::now()->subYears(3),
                'status' => 'completed',
                'score' => 85.5,
                'findings' => 'Visi dan misi sudah jelas dan terukur, namun sosialisasi masih perlu ditingkatkan.',
                'recommendations' => 'Meningkatkan sosialisasi VMTS kepada seluruh pemangku kepentingan.',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(3),
                'updated_at' => Carbon::now()->subYears(3),
            ],
            [
                'id' => 2,
                'accreditation_id' => 1,
                'standard_id' => 4,
                'title' => 'Evaluasi Standar SDM',
                'description' => 'Evaluasi capaian standar Sumber Daya Manusia',
                'evaluation_date' => Carbon::now()->subYears(3),
                'status' => 'completed',
                'score' => 82.0,
                'findings' => 'Kualifikasi dosen sudah baik, namun jumlah masih kurang memadai.',
                'recommendations' => 'Merekrut dosen baru dengan kualifikasi yang sesuai kebutuhan program studi.',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subYears(3),
                'updated_at' => Carbon::now()->subYears(3),
            ],
        ];

        DB::table('accreditation_evaluations')->insert($evaluations);
    }
}
